#!/bin/bash

set -ev

# setting up default for environment variables
SERVER_NAME=${SERVER_NAME:-example.com}
DB_HOSTNAME=${DB_HOSTNAME:-$DB_PORT_3306_TCP_ADDR}
DB_USER=${DB_USER:-$DB_MYSQL_USER}
DB_PASSWORD=${DB_PASSWORD:-$DB_MYSQL_PASSWORD}
DB_DATABASE=${DB_DATABASE:-$DB_MYSQL_DATABASE}

# making sure only one instance of this script run

if [ ! -f /var/run/install_worpress.pid ];then
    echo $$ > /var/run/install_wordpress.pid
else
    echo "install_wordpress is already running"
    exit 1
fi

echo "$(date): Installing  Wordpress from repository $GIT_SSH_URL for $SERVER_NAME"


# setting ssh key auth to the remote repository

ssh-keyscan -t rsa github.com  > /root/.ssh/known_hosts

if [ -d "/root/deploykeys" ];then
    cp /root/deploykeys/$GIT_DEPLOY_KEY /root/.ssh/
    cp /root/deploykeys/$GIT_DEPLOY_KEY.pub /root/.ssh/
    chown root:root /root/.ssh/$GIT_DEPLOY_KEY
fi


# test wether it is an install from scratch or an upgrade
if [ -f "/tmp/last_wordpress" ]; then
    NEW_INSTALL=0
else
    NEW_INSTALL=1
fi

# Installing wordpress
echo "Retrieving a Wordpress project from a remote git repository"

if [ "$NEW_INSTALL" = 1 ]; then

    if [ "$GIT_SSH_URL" != '' ]; then
        # from a git repository using SSH. It is assumed appropriate credentials are set up

        cd /usr/share/nginx
        git clone $GIT_SSH_URL www
    fi
    echo "performed: git clone $GIT_SSH_URL www"

elif [ "$NEW_INSTALL" = 0 ]; then

    cd /usr/share/nginx/www
    git pull
    echo "peformed: git pull"

else
    echo "nothing installed"
fi

#  Removing the deployed key

if [ -f "/root/.ssh/$GIT_DEPLOY_KEY.pub" ]; then
    echo "removing the public key"
    rm /root/.ssh/$GIT_DEPLOY_KEY.pub
fi

if [ -f "/root/.ssh/$GIT_DEPLOY_KEY" ]; then
    echo "removing the private key"
    rm /root/.ssh/$GIT_DEPLOY_KEY
fi


echo "Backing up existing wp-config in case variables have been manually added to it"
if [ -f /usr/share/nginx/www/wp-config.php ]; then
  cp /usr/share/nginx/www/wp-config.php /usr/share/nginx/www/wp-config.php.bak
fi


# Here we generate random passwords (thank you pwgen!). The first two are for mysql users, the last batch for random keys in wp-config.php
# configuring wp-config with DB connection details from linked container then generate random password for keys
echo "Replacing database connection details in wp-config with $DB_DATABASE, $DB_HOSTNAME, $DB_USER, DB_PASSWORD (hidden)"
sed -e "s/database_name_here/$DB_DATABASE/
s/localhost/$DB_HOSTNAME/
s/username_here/$DB_USER/
s/password_here/$DB_PASSWORD/
/'AUTH_KEY'/s/put your unique phrase here/`pwgen -c -n -1 65`/
/'SECURE_AUTH_KEY'/s/put your unique phrase here/`pwgen -c -n -1 65`/
/'LOGGED_IN_KEY'/s/put your unique phrase here/`pwgen -c -n -1 65`/
/'NONCE_KEY'/s/put your unique phrase here/`pwgen -c -n -1 65`/
/'AUTH_SALT'/s/put your unique phrase here/`pwgen -c -n -1 65`/
/'SECURE_AUTH_SALT'/s/put your unique phrase here/`pwgen -c -n -1 65`/
/'LOGGED_IN_SALT'/s/put your unique phrase here/`pwgen -c -n -1 65`/
/'NONCE_SALT'/s/put your unique phrase here/`pwgen -c -n -1 65`/" /usr/share/nginx/www/wp-config-sample.php > /usr/share/nginx/www/wp-config.php

# Boostraping Nginx Helper Wordpress plugin's log
mkdir -p /usr/share/nginx/www/wp-content/uploads/nginx-helper
touch /usr/share/nginx/www/wp-content/uploads/nginx-helper/nginx.log
chown www-data:www-data /usr/share/nginx/www/wp-content/uploads/nginx-helper/nginx.log


echo "Wordpress installed on $(date)" > /tmp/last_wordpress

if [ -f /var/run/install_worpress.pid ];then
    rm /var/run/install_wordpress.pid
fi

exit 0
